name: build

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Go 1.12
      uses: actions/setup-go@v1
      with:
        go-version: 1.12
      id: go
    - name: Check out code
      uses: actions/checkout@v1
    - name: Install ecpg
      run: sudo apt install libecpg-dev -y
    - name: Vet
      run: go vet ./...
      env: 
        GO111MODULE: on
    - name: Test
      run: go test ./... -race -coverprofile=coverage.txt -covermode=atomic
      env:
        GO111MODULE: on